### PR TITLE
Sgratzl/rest cache

### PR DESCRIPTION
**Pull request by sgratzl**
add option in the config to record or use a cache for all the incoming rest requests. see `restCache` config option. Only 200 get requests that result in a regular JSON flie are cached if enabled. The cache key is a combination of the url and its hash value.

### CODE REVIEW

**Comment by sgratzl** [comment]
> When using the cache the first time i guess the response is cached internally nonetheless (rest or file request) as I only recognize the LOG output 'use cache cache... the very first request.

take a look at your network requests page, then you can verify whether he has taken it from the cache or not



> Can you elaborate on the namespace once again why there are two accessors of namespace[0] and namespace[1]

you mean this line? `_rest_cache(namespace)[0]`

**Comment by sluger** [comment]
> you mean this line? _rest_cache(namespace)[0]

yes

**Comment by sgratzl** [comment]
> you mean this line? _rest_cache(namespace)[0]
> 
> yes

the method `_rest_cache` returns a tuple containing two items. The first one is the `safe´ method the other the `load` method

**Comment by sluger** [comment]
thanks

**Comment by sluger** [comment]
@thinkh you may have a quick look at this and merge it if approved. otherwise let me know then i merge it myself.

**Pull request merged**
