### PR TITLE
added new extension point to run functions right after server started

### PR DESCRIPTION
**Pull request by lehnerchristian**
# Description 
with this change we can register extensions with the extension point `after_server_started` which is executed right after the server has started

this has the advantage that we can run functions right when the server is ready instead of running them lazily on the first user request

can be used to fill in-memory caches, create server-rendered plots, etc.

# Usage

we can register a new extension in an `__init__.py` like this
```python
registry.append('after_server_started', 'fill_caches', 'my_python_package.script_file', {
    'factory': 'fill_caches'
  })
```

the `script_file` in `my_python_package` would define a factory function which returns a new function which is then executed by the phovea_server ([here](https://github.com/phovea/phovea_server/pull/101/files#diff-7afc17e3223342e6d96b4219d3d550c0R231-R232)):
```python
def fill_caches():
  def prepare():
    rows = query_some_data()

    for row in rows:
      build_cache(row)

  return prepare
```

### CODE REVIEW

**Comment by anita-steiner** [comment]
> Before we merge this I would like to know the following things:
> 
> 1. How does the server behave when you have one (or multiple) long-running tasks? Are they stalling the server?
> 2. In case the server is not stalled and accepts API requests while processing the task (e.g., importing the data) in the background: How would an API request that requires imported data know that the import is still on-going or all data is imported? Would that particular API request then be stalled?
> 
> Maybe a job in a [processing queue](https://github.com/phovea/phovea_processing_queue/) might be the better option for such long-running tasks?

I think it's also ok to run them in a separate thread - so we don't need the processing-queue; the question is, if this is this should be part of the phovea_server or is this the task of the plugin

**Comment by lehnerchristian** [comment]
I think this should definitely be the task of the server, because otherwise it's too easy to block the whole server, as holger mentioned

I've tested this in a deployed instance with long running tasks (e.g. image generation) and a lot of data.

However something still blocks when running with multiple threads. my results were:

| cached? | time in seconds | threads |
|---|---|---|
| No plots cached | 1708.785050868988 | 1 |
| with plots cached | 4.489455938339233 | 1 |
| No plots cached | 1673.4740619659424 | 4 |
| with plots cached | 4.151928901672363 | 4 |

so something's still wrong. maybe we can have a look next week together. I have a simpler implementation with the same threadpool which is really nearly 4 times faster, but here something's different

**Comment by lehnerchristian** [comment]
Threading should be done by the application itself, because the server does not know anything which data it needs and how many threads it should start

I also think if the server is currently blocked it should somehow be able to return a page indicating that it's busy (ideally querying the server periodically and reloading when the server has loaded, as we already discussed in a personal meeting, @thinkh ), but this would be a separate ticket, I think

for now I have at least added some more comments, as @thinkh and I discussed today

**Comment by lehnerchristian** [comment]
in a meeting we discussed that we'll think again for another solution for performing actions (e.g. generating plots or performing expensive DB queries and caching them) when the server has started

**Comment by lehnerchristian** [comment]
@anita-steiner and me agreed in a personal meeting on checking how to run the hooks asynchronously in Python such that the server does not have to wait

**Comment by lehnerchristian** [comment]
@anita-steiner , I had a personal meeting with @thinkh and showed him how the current version with running the `after_server_startup` hooks work.

[Here I've created a wiki page](https://wiki.datavisyn.io/phovea/additional/after-server-started-hooks)

Currently the hooks are run in a new thread, however we could also  run them in a new process enabling the user to multithread on an application level. Holger and me didn't have a strong opinion if we should use threads or processes right now, but if we need to multithread the hooks we can always change that those hooks are run in a separate process.
That said I'm not sure if my use-case would still work with a separate process, since a separate process has its own memory and we're caching things on server startup in memory

If you want to test this (please test it) you can for example add the following function to `phovea_server.server.py`:
```
def delay_hook(hook):
  import time
  print("Still running...")
  time.sleep(10)
  print("Running the next hook now...")
  hook()
```

Then on the line where the `hook()` is actually called (https://github.com/phovea/phovea_server/pull/101/files#diff-7afc17e3223342e6d96b4219d3d550c0R240) you can simply call `delay_hook(hook)`

Now when you add some dummy hooks like
```
registry.append('after_server_started', 'test1', 'snpology.plots', {
  'factory': 'test_hook'
})

registry.append('after_server_started', 'test2', 'snpology.plots', {
  'factory': 'test_hook'
})

registry.append('after_server_started', 'test3', 'snpology.plots', {
  'factory': 'test_hook'
})
```

with this implementation:
```
def test_hook():
  def test():
    return True

  return test
```

**Pull request merged**
